Check if layer name is referring to registration mark or print layer
fablabnbg/inkscape-silhouette pull request #252
Opened 2023-08-14 15:05 UTC by mofosyne

if so then skip

2023-08-14 15:11 UTC, mofosyne commented
Have not updated readme for it, but may consider if needed.

2023-08-14 18:14 UTC, t0b3 requested changes

2023-08-14 18:14 UTC, t0b3 commented on sendto_silhouette.py
> +                # Check if layer name is referring to registration mark or print layer
the whole check would only be needed on `Group`s, right? if so, move to Group logic below... this will help to speed things up

2023-08-14 18:14 UTC, t0b3 commented on sendto_silhouette.py
> +                    layer_label_name = node.attrib[LAYER_LABEL_ATTR_KEY]
you may access the layer's label through `node.label` property 
see https://gitlab.com/inkscape/extensions/-/blob/master/inkex/elements/_base.py#L535-538

thus simply use
```
if node.layer:

2023-08-15 00:42 UTC, mofosyne commented
Okay, correction done

2023-08-16 05:38 UTC, t0b3 requested changes

2023-08-16 05:38 UTC, t0b3 commented on sendto_silhouette.py
> +                LAYER_LABEL_ATTR_KEY = '{http://www.inkscape.org/namespaces/inkscape}label'
`LAYER_LABEL_ATTR_KEY` isn't needed anymore, correct?

2023-08-16 05:38 UTC, t0b3 commented on sendto_silhouette.py
> +                        self.report(f"layer '{str(node.label)}' is a registration mark layer - skipped", 'log')
`node.label` already returns string type, no need to call `str()`

2023-08-16 05:38 UTC, t0b3 commented on sendto_silhouette.py
> +                        self.report(f"layer '{str(node.label)}' is a print layer - skipped", 'log')
`node.label` already returns string type, no need to call `str()`

2023-08-16 10:44 UTC, mofosyne commented
Good catch. All resolved.

2023-08-16 20:40 UTC, merged